### ISSUE TITLE
SNMP Monitoring

### ISSUE THREAD

**Issue by KUBAllen** [jgyates/genmon#313] opened 2019-09-12 19:13 UTC
Just putting this out there to see what others' interest level is. Would it be possible to add an SNMP module to Genmon that could be polled for vital stats like monitor health, generator status, fuel level, etc? This would allow a network monitoring software like Solarwinds or PRTG to send alerts if connectivity is lost or if there is an issue? We run Solarwinds as our network monitoring platform and would be nice to see the generators in that dashboard.

Thanks!

**Comment by mac067783** [comment] 2019-12-04 00:57
I would like to second the motion for SNMP support, or if the python script that was created for Nagios can be modified for PRTG, that would work too. Would there be a way to publish "1 liners" of simple python scripts that return single numerical values, ie. 1 script for status,1 for rpm, 1  for voltage, etc...I have both the Genmon, prtg, and an evo2 controller id be willing to test and POC with you.

**Comment by liltux** [comment] 2020-01-30 19:45
@jgyates I was testing around with this and found using the python script for ClientInterface.py and commenting out the loop for input and using a directed value in the script.  I was then able to use a bash script to call the python program, filter out the desired output using the bash script, and Extend it out to SNMP on the Pi.  I was using #277 as reference and able to do some other googling to make it work.  Although I dont have any commercial software to test with but the snmpwalk command shows it works.

**Comment by liltux** [comment] 2020-01-30 19:55
@jgyates never mind, I found it.

**Comment by KUBAllen** [comment] 2020-01-31 22:19
@liltux Would you be willing to share your code on this? I'm a network admin by trade, but I might be able to stretch up above layer 3 and get this working in our environment... ;)

Thanks!

**Comment by jgyates** [comment] 2020-01-31 22:24
The more code the merrier. :)

For what it is worth, I will likely have something working with the main code base in the next few days. The new add on is working , I just need to test, integrate with the installer / upgrader, add more OIDs and document.

**Comment by liltux** [comment] 2020-01-31 22:33
@jgyates prolly better to wait for your official release.  Mine was just a work around that I was playing with off of #277 post.  I found it works and just wanted to share.  I am sure with the python libraries there was/is a cleaner way to do it.  It was fun playing around in the code.  I found there was a permissions issue and had to use sudo within the bash scripst for snmp to extend all the data.

**Comment by KUBAllen** [comment] 2020-01-31 22:38
I'll wait patiently then. :) I feel like a leech not knowing any relevant languages to contribute. Thanks for all you do on this project!

**Comment by jgyates** [comment] 2020-02-02 06:04
I have checked in V1.14.00 that includes an add on for SNMP monitoring. 

https://github.com/jgyates/genmon/wiki/1----Software-Overview#gensnmppy-optional

Let me know if you have any questions or issues. This release also has a feature that will send you an email if a software update is available.

**Comment by jgyates** [comment] 2020-02-02 06:29
FYI: The update may take slightly longer since a new library has to be installed during the update process.

**Comment by mac067783** [comment] 2020-02-02 14:31
I’ve tried installing, enabling, and configuring a community string, however when I try to SNMPWalk it, snmpwalk times out saying no response from the Genmon.  Any additional steps that need to be performed?

~Kyle

**Comment by jgyates** [comment] 2020-02-02 15:36
@mac067783 , no additional steps. Just make sure the IP used in snmpwalk is the same IP of your pi and the community string matches. Errors are logged to /var/log/gensnmp.log 

you can also edit the config file /etc/genmon/gensnmp.conf and set debug = True. this will include additional info in the log. Just be sure to set debug = False once you are finished as this adds a lot of additional writes to your SD card which over an extended period of time could shorten the life of your SD card.

Here are some things to try:

Can you ping the same IP address?
Can you ssh into the pi with the same IP address?
Does the community string specified in snmpwalk match the community string in gnemon snmp setup?
What program and operating system are you using to run snmpwalk? (I have used the command line version built in MacOS and the program MIB Browser (free version: https://www.ireasoning.com/downloadmibbrowserfree.php)

If you use a gui version, make sure you set the community string. 

are you using the default community string in your test

**Comment by mac067783** [comment] 2020-02-02 16:25
I’ll try debugging and see what I can find. 

To answer the questions below: 
Yes, I can ping the IP address
Yes, can also SSH into the same IP
Community strings match
Using macOS via terminal
Using a custom snmp community string not the default of public. 



~Kyle

**Comment by jgyates** [comment] 2020-02-02 16:56
I posted a minor update (V1.14.01). This corrects an issue where the wrong data was returned for one OID.

**Comment by mac067783** [comment] 2020-02-02 17:36
I have my Genmon behind a firewall and figured out that if you don’t have SSL something is blocked during which doesn’t allow snmp to work correctly. Once I opened that up temporarily everything works correctly. 

~Kyle

**Comment by jgyates** [comment] 2020-02-02 17:37
Glad to hear it is working, thanks for the feedback. Let me know if you have any other issues.

**Comment by jgyates** [comment] 2020-02-04 02:52
I am going to close this thread for now, feel free to post here if you have related questions or issues.

**Closed by jgyates** 2020-02-04 02:52 UTC
Labels: enhancement, question

**Comment by TopBanana123** [comment] 2021-10-12 01:06
Hey, I have a quick question. I already have SNMP configured on my Pi. I've modified the /etc/snmp/snmpd.conf file

Do I need to remove this configuration, or can they both be active? I've enabled SNMP via the WebUI with a different community string, however I cannot monitor Genmon with that, and the old string I used for general monitoring still works

**Comment by jgyates** [comment] 2021-10-12 01:20
Hi @TopBanana123 

I don't know for sure since I have not tried that myself, but my guess is that they are not compatible. The genmon add-on uses the python [pysnmp library](https://pysnmp.readthedocs.io/en/latest/) to support snmp. You can try it with the same community string. How the pysnmp library was designed is dependant on if this will work.

**Comment by TopBanana123** [comment] 2021-10-12 01:26
Thank you, I tried disabling snmpd with `sudo /etc/init.d/snmpd stop` and then toggling SNMP add-on, and now its working
