### ISSUE TITLE
G-Panel Communication issues

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#689] opened 2022-03-23 16:04 UTC
Asking to see if anyone is using Genmon on G-panel controllers and running into similar issues?

### Expected Behavior

Start and Stop Generator Remotely

### Actual Behavior

Can send the Start command, but having Comms issues and not recieving good Modbus responses

### Steps to Reproduce (including precondition)

Operating Genmon on G-Panel or MD/MG type generator

### Screenshot or Pictures relating to the problem (if possible)

![image](https://user-images.githubusercontent.com/17954856/159742835-226716c5-9aed-4a82-a296-e560d8916054.png)
V1.16.05
![image](https://user-images.githubusercontent.com/17954856/159743352-d25a4dfe-7351-475d-9e4e-dcdba1b4aea1.png)
V1.18.09

### Your Environment

- Generator Model: MD400 and MG150
- Genmon Logs: Cannot due to no internet access at Generator access
- Genmon Version: one is operating  V1.16.05 the other is V1.18.09

**Comment by liltux** [comment] 2022-03-23 16:35
![image](https://user-images.githubusercontent.com/17954856/159750014-6ff32c4c-58e0-45ba-b180-9e3abc3e78f1.png)

According to my documentation this should be 576? Not 566?  I will test and see and let you know.

**Comment by liltux** [comment] 2022-03-23 16:47
@jgyates Double check me please, but I change the "0236" to "0240" and restarted Genmon.  This is my monitor page reporting after the change:

![image](https://user-images.githubusercontent.com/17954856/159752297-7454714e-225c-4c14-8eaf-3aef3ec97d2c.png)

**Comment by liltux** [comment] 2022-03-23 16:52
![image](https://user-images.githubusercontent.com/17954856/159753372-3fbb8963-d4fd-453b-afda-ca3263319053.png)

**Comment by jgyates** [comment] 2022-03-23 16:55
Look like a bug.

**Comment by jgyates** [comment] 2022-03-23 16:55
I guess this effects H and G panel systems.

**Comment by liltux** [comment] 2022-03-23 16:58
Yes and No.  Evidently H panels do not throw an exception for that register, but not sure of the data.  Only G panels throw the exception.  We are getting a guy on site to test the remote start/stop buttons this afternoon.  I am guessing the exceptions should correct the Modbus comms and allow the WebUI to operate properly.  I will see and let you know.

**Comment by jgyates** [comment] 2022-03-23 17:06
Let me know how the test goes. I can remove that entry if needed. That value is read but never used to display any data, probably because I could not make any sense out of the data that was read.

**Comment by liltux** [comment] 2022-03-23 21:20
@jgyates that corrected my modbus exceptions.  We still cannot remote start/stop.  This is the first time doing this with a Gpanel.  I was watching the register page while someone else was activating the start command.  The register for Quiet Test was changing but not the 3 registers for Start/Stop.  Curious why this would be happening?  Attached is a copy of the registers.
[10MinuteModbus.pdf](https://github.com/jgyates/genmon/files/8336765/10MinuteModbus.pdf)

**Comment by liltux** [comment] 2022-03-23 21:35
[10MinuteModbusHPanel.pdf](https://github.com/jgyates/genmon/files/8336842/10MinuteModbusHPanel.pdf)
Here is the registers from a working Hpanel.  Notice the Start/Stop register 1 changes, but does not on the previous example with the Gpanel controller.

**Comment by jgyates** [comment] 2022-03-23 22:40
Regarding the change the modbus register to 0x240 or did you remove the command? I will change the code to what you did.

This implies that the G-Panel and H100 have different commands. The software is assuming they both have the same set of commands for remote modbus control. I don't have any additional data for a G-Panel remote commands. We could run some tests to determine the G-Panel commands needed.

**Comment by jgyates** [comment] 2022-03-23 22:45
Another thing to test is the Ack Alarm functionality. That is a command that assumes both H and G act the same way.

**Comment by liltux** [comment] 2022-03-24 01:27
I did change the register value to 0x240.  I figured it can be in there until we can figure out the data but 0x240 is valid and does not return an exception.
According to the Modbus information it states the same for both controllers.  What I would like to try is with Genmon running and recording modbus data, using genlink remote start and stop the gen. Verify which registers are used to start/stop the gen.  Hopefully I will get a chance over the next couple of days.  I will let you know.  Thanks for the help.

**Comment by liltux** [comment] 2022-03-25 20:18
@jgyates  I have it figured out.  The G panel controllers are either Standalone or Parallel.  The ones I am working with are Parallel.  Which means, all of the data registers are the same, and even the remote start/stop.  But in our case the SC is over writing the register as soon as we write to it.  Or it is blocked.  It is a valid request as I am not seeing an exceptions or modbus errors.  It just the PM-P(arallel)C(ontroller) only accepts a start request from the System Controller (SC).
The System Controller has a different address mapping, but does allow a passthrough using higher modbus ranges for the different gens on the system.
Also note, everything works except remote start/stop commands.  Alarm Acknowledge works.
I hope this makes sense.  I am not sure the best way to approach this yet.  But I appreciate your work and help.

![image](https://user-images.githubusercontent.com/17954856/160195048-9dd0eba1-b645-4e37-8fc9-66c1a906d02f.png)
[Modbus MPS G panel.xls](https://github.com/jgyates/genmon/files/8353599/Modbus.MPS.G.panel.xls)
[Modbus Stand Alone G panel.xls](https://github.com/jgyates/genmon/files/8353600/Modbus.Stand.Alone.G.panel.xls)

**Comment by jgyates** [comment] 2022-03-25 22:12
So every thing works for G-Panel in standalone, but in Parallel mode the remote commands do not work? Is that correct?

Also, I could add an option to address the parallel generators by the addressing scheme above if you thing that would be useful. Basically I would just add an advanced parameter that would get added to the address for the remote commands (1 = add 4096, 2 = add 8192). This is just adding 1 or 2, etc to the top 8 bits of the modbus address for the remote commands.

**Comment by liltux** [comment] 2022-03-26 02:41
I am waiting to test some more with a G-Panel in standalone.  AS for the G-Panel configured as a Parallel Controller, I don't think it is as simple as what you suggest.  The addressing scheme is used if the RPi is connected to the system controller, if it is directly connected to the Gen, it would be the standard address.  What I think is happening is either the Generator does not accept start commands coming from a master other than the system controller.  Or, in fact, the system controller sees the start command, realizes it did not do that, immediately stops the gen.  The later almost makes sense, due to the Event Logs, which stated the gen started and 4 secs later stopped, yet it never actually started at all.  
However, I think if the RPi was connected to the System Controller G-panel and a start command was issued, it would tell the System Controller to start the system, which would be all the gens on the paralleled bus.  Which would probably be the desired affect anyways.  In that case we would want to use the scheme to view individual Gen data and status registers, but the control would go to the System Controller.
As more thought and discussion maybe needed to determine the correct path if any is needed.  Curious of the most efficient use of the RPi and Genmon.  Thoughts?

**Comment by jgyates** [comment] 2022-03-26 18:14
I agree that having a single RPi connected to the Parallel controller makes a lot more sense from an integration perspective. I can envision an architecture that a single RPi could be used to host multiple instances of genmon with one instance being the only one issuing commands and the other instances of genmon running are simply passing on modbus requests and sending modbus responses back.
Also, the G and H panel doc has some info on the start commands for parallel controllers.

<img width="885" alt="Screen Shot 2022-03-26 at 2 01 00 PM" src="https://user-images.githubusercontent.com/4513286/160251909-226b6d68-7f6e-4950-b25b-f0b415481f1b.png">

The software current uses the PM-CG Start and PM-CG Stop commands to start and stop the generator (in the commands exposed to the web interface). It does *not* export to the web interface any of the PM-GCF commands, however you can issue a "startparallel" command using the ClientInterface.py program.

     python ClientInterface -a 192.168.1.10

To start parallel type:

    generator: setremote=startparallel

To stop, type:

    generator: setremote=stop

to exit ClientInterface.py type:

     exit

**Comment by liltux** [comment] 2022-04-01 17:45
@jgyates I have not been able to do any further testing as of yet.  But I do have a question.  Referncing to what we have discussed so far,  one on the G-panels I am working with is programmed as a standalone and not part of a System Controller.  Previously, that Generator accepted the start command but in the WebUI the Stop button never became active.  Looking through the code I found this in the genmon.cs file:
![image](https://user-images.githubusercontent.com/17954856/161314599-5c630547-8418-4611-9e67-ff3258bb00f5.png)
I believe this is what sets the state of those buttons.  It is based off of these specific key-word states.  I think the G-Panel is a different wording and that is why the stop button does not go active, the default is to leave the startremote active.  I think that will correct that issue if I can get the a better key-word to add to that case statement or additional.  Your thoughts?

**Comment by jgyates** [comment] 2022-04-01 20:38
That could be the issue, but I suspect the issue is something else. If you issue this URL

http://192.168.1.10:8000/cmd/getbase

this will show a single word: EXERCISING, RUNNING, OFF, etc..

This case statement is setting the buttons based on this value. What is the value you read from the URL?

The default case should be OFF or READY, which implies the generator is off and could be started. This value returned is also used to set the colors on the web menu UI.

if you send me a set of G-Panel registers for stopped and running I can test this and see if I can duplicate and figure out the issue.

**Comment by jgyates** [comment] 2022-04-01 20:59
it works for me with H-Panel registers testing. It could be something in genmon H / G Panel code

https://github.com/jgyates/genmon/blob/188805660ef1e712a22f94772165841f4d64c03a/genmonlib/generac_HPanel.py#L2366

The above function process the data from the H-Panel and G-Panel controllers and returns the single word response in the getbase URL

**Comment by liltux** [comment] 2022-04-05 12:59
@jgyates the /cmd/getbase does work.  I am still needing to test and verify the actual behavior of the unit under these remote commands.

> if you send me a set of G-Panel registers for stopped and running I can test this and see if I can duplicate and figure out the issue.

To be clear, I can download registers with the unit in auto and off, then download registers with unit in auto and running.  Then send you both sets of files for you the test against?

I am thinking using a Genmon for each generator is sufficient.  The data from the system controller would just be redundant and add complexity that is not required.  The only issue so far that I am seeing is with the remote start command, but at minimum I could add a Genmon on the SC and send it a request remotely to start/stop the system.  Is the setremote=start/stop/startparallel available through the web api ~/cmd/setremote=start?

**Comment by BillyEll** [comment] 2022-04-12 22:25
I have 2 -100kw generators connected to P&L Controller. I would love to be able to start/stop the generators remotely via ModBus. I stumbled across this while trying to find any info on their ModBus mapping. They look like they are using Power Zone controls, does anyone happen to have a ModBus Registry map for these things they would mind sharing? Ideally start/stop them independently. I was trying to talk/control these from Ignition Automation, so that in the case of an extended power outage, I could see if I require both generators, and if not shut one down, after maybe an hour, fire the other back up and then shut the other one down. Any advice would be appreciated. I will have to go try and catch up as I have a home generator as well and the Genmon might be pretty handy for it and I already have a Raspberry Pi I could use.

**Comment by liltux** [comment] 2022-04-13 00:01
@BillyEll, with the power zone controllers they have built-in load manager.  I have not looked into it much because I have not had to use.  But I am sure you could program the controls that based on levels of load run one and not both gensets.  Then also use hour counts to switch between the 2.  I know it is a feature of some sort with the powerzones but again I am not very familiar with that feature.  Let me see what I can come up with.  
In a parallel application, I think you will find it hard to start/stop a single unit but I am not sure either.  You can email me, liltux (at) lilltux (dot) com, and I can get you the modbus map for the Powerzone.

**Comment by liltux** [comment] 2022-04-14 15:47
@jgyates I have an update on the Gpanel as Standalone controller, no System Controller.  It will accept a button press for start command and start.  The page refreshes but does not give the ability to press the stop button for stop command.  I can however, send setremote?setremote=stop and the gen will stop.  So I know the stop command will and does work, just need to get the webserver to see the generator as running.  Engine State and Generator Status both state unit is running, and getbase only returns "ready".
Engine State : "Run serial_start(Genlink)"
Generator Status : "Warmed Up, Holdoff alarms enabled"
I got as far as the getbase request for page refresh and button placement, but in the controller.py I could not clearly see how to make "Run serial_start(Genlink)" to return as enginestate=running.  I think if that would happen the page would refresh and a running state, getbase = RUNNING, would allow the Stop button to be accessible and sent the stop command.

**Comment by liltux** [comment] 2022-04-14 17:10
![image](https://user-images.githubusercontent.com/17954856/163439106-9393f22a-4fec-4a81-af9d-193b09304023.png)
![image](https://user-images.githubusercontent.com/17954856/163439192-16971911-9d76-44c7-81e6-9cf15d2bad0f.png)
![image](https://user-images.githubusercontent.com/17954856/163439219-dd96b83a-b926-47df-b391-b318102d559c.png)
First image was Starting using web cmds, then stopping with web cmds.

**Comment by jgyates** [comment] 2022-04-14 17:33
@liltux 

Thanks. I checked in a fix that should correct the getbase state, which should allow the web interface to show the state of the buttons correctly. If you can it would be helpful to get a snapshot of the registers from the About page when running via serial start. This would allow me to test this as well to make sure the fix is working.

Thanks
Jason

**Closed** 2022-04-14 18:47 UTC
Labels: Industrial

**Comment by liltux** [comment] 2022-04-14 19:31
@jgyates I just tested startparallel command sent to the G-Panel with a System Controller for parallel application.  The status changed to "Exercise with Transfer", but nothing started.  Anyways that would have been a disaster if it transferred.  So I immediately sent the stop command.  I am going to see about getting a Genmon on the System Controller and see what we see.  If I do not run the genserv.py (web app), can I still send commands/requests to the serial server on the 9XXX port using clientinterface.py.   Concerned the address mappings for the system controller could cause issue with genserv.py.

**Comment by jgyates** [comment] 2022-04-14 19:38
Yes
