### ISSUE TITLE
Industrial Gens

### ISSUE THREAD

**Issue by darkstar2002** [jgyates/genmon#98] opened 2018-04-19 18:17 UTC
Has anybody tired using this on the Industrial versions?
We have a 550kw, 400kw, and a 175kw.

I know they have a db9 serial port on the front of the controllers.

**Comment by jgyates** [comment] 2018-04-19 19:06
Not that I am aware of. The software is designed to work with Either Nexus Controller or the Evolution Controller. After a quick seach it looks like the industrial version use the H-Panel for the controller. This is not supported by the software, however the H-Panel does appear to have a documented modbus interface which should make it easier to support.

**Comment by jgyates** [comment] 2018-04-23 20:33
@darkstar2002 

If you are interested in industrial version being supported, I have added a program to the repository that would provide the first step in adding the industrial generators as a supported generator.  It would require you to create a cable and run a program connected to the generator to get the contents of the controller registers for each generator. From there I would start the process of adding the code to support this generator. I would anticipate this process could take a few months, depending on the difficulty involved in interpreting the existing documentation online.

Let me know if you are interested and I can provide additional instructions.

**Comment by darkstar2002** [comment] 2018-04-24 14:36
I am interested in doing this.  It may be a week or so before I will have the time to get to the generators.

**Comment by jgyates** [comment] 2018-04-30 18:04
@darkstar2002 
Here are the first steps:

1) Download this manual: https://gensetservices.com/wp-content/themes/gensetservices/PartsPDFs/0F3750.pdf
2) Download the genmon repository onto the raspberry pi or PC
3) In the repository, move the file /genmon/OtherApps/modbusdump.py up one directory
        cd ./genmon/OtherApps
       cp ./modbusdump.py ..

We will run this program with the cable attached to the controller to validate communication and get the contents of the modbus registers. Once this is validated and we have the contents of the registers I can begin integrating support for this controller in the software.

4) Attach a cable from the 9 pin port on the the front to a computer that can run python (raspberry pi, or PC). Attach the other end to the raspberry pi or PC

From here we will run the modbusdump program : 

The syntax for the program is:

python mobusdump.py -r <Baud Rate> -p <serial port> -a <modbus address to query> -s <start modbus register>  -e <end modbus register>

Note the -a parameter is in hex and the -s and -e params are in decimal.

If you refer to the manual in the link above you can get the modbus slave address (page 21, default could be 100 or 64 hex), baud rate, see page 21). The serial port is dependent on if you are on a PC (windows or linux) or raspberry pi (/dev/serial0).

Once we get all of this info we will need to select a start and end register to probe (parameter -s and -e). For our initial test lets start with -s 140 and -e 142:

     python mobusdump.py -r 9600 -p /dev/serial0 -a 64 -s 100  -e 101

Copy and past the output of these test to this thread. Let me know if you have any questions.

**Comment by darkstar2002** [comment] 2018-04-30 20:15
I have tried running this on 2 pc's   one windows and one linux.   I get an error about the libs not found.   I did move the file up one directory.

**Comment by jgyates** [comment] 2018-04-30 20:32
I forgot to mention that you will need to install the python serial library. Run these commands from the linux to install all the libraries needed for genmon (for this test, you only need crcmod and python-serial, and pip to install the libraries):

     sudo apt-get update
     sudo apt-get install python-pip
     sudo pip install crcmod
     sudo pip install configparser
     sudo apt-get install python-serial
     sudo pip install Flask

**Comment by liltux** [comment] 2018-04-30 23:14
I am a big fan of this project and thought I could offer some help in this area.  It is the modbus mapping for generac industrial generators.  see the zipped file.

[Modbus Map Generac Industrial.zip](https://github.com/jgyates/genmon/files/1962458/Modbus.Map.Generac.Industrial.zip)

**Comment by MichaelB2018** [comment] 2018-05-01 02:08
I would love to help as well to improve this further, but I have a residential unit. @liltux, do you have that maps?

**Comment by darkstar2002** [comment] 2018-05-01 14:11
Got things working.   When trying different start and stop ranges I get a error reading device: byte must be in range(0, 256)

**Comment by jgyates** [comment] 2018-05-01 14:30
Great! Couple of questions:

1) What is the command line your are using
2) The program will log errors to a file named mymodbus.log in the current working directory. Can you include this file?
3) Does your controller screen tell you the modbus address? If yes what is the value?

**Comment by darkstar2002** [comment] 2018-05-01 14:52
python.exe modbusdump.py -r 9600 -p COM4 -a 100 -s 140 -e 142
The log does not add anything when this error comes up.  If I leave my adapter off it says can not open the port

Slave address is 100 9600 buad

**Comment by jgyates** [comment] 2018-05-01 15:37
I just checked in an updated version of mymodbus.py, the library that the program is using to handle the modbus details. This should give me more info on the problem. This error is caused by trying to put  a value larger than 255 in a byte array. I am not sure if this is happening on the send or receive but the new version of mymodbus.py will let me know so I can correct this problem. Update to the latest software and let me know the results. It should put the error with more details on mymodbus.log. Let me know if you have any questions.

**Comment by jgyates** [comment] 2018-05-01 15:55
Another question: 
What version of python are you running? You should be able to type:

     python -V

and it will show you the version. There has been little testing with version 3.x. 2.7 is recommended.

**Comment by darkstar2002** [comment] 2018-05-01 16:14
I am running 2.7 on windows.  I am working on setting up a virtual linux for the laptop.   
the program says ok no info returned.   Here is log file.
[mymodbus.log](https://github.com/jgyates/genmon/files/1964358/mymodbus.log)

**Comment by jgyates** [comment] 2018-05-01 16:17
ok. I  think I see the problem. Give me a few min to fix it.

**Comment by darkstar2002** [comment] 2018-05-01 17:18
Ok got it working.

Address is : 64
Start Register : 140
Start Register : 142
008c:0000
008d:007d
OK

**Comment by jgyates** [comment] 2018-05-01 17:27
Excellent! Now that we have validated communications lets run this command line:

     python.exe modbusdump.py -r 9600 -p COM4 -a 64 -s 0 -e 400

You can redirect this to a file if you like and just send the file:

     python.exe modbusdump.py -r 9600 -p COM4 -a 64 -s 0 -e 400 > out.txt

This will give me what I need to emulate your generator. Send me this once you can run it.

When you can, I will also need a dump of the registers with the generator running.

Ideally it would be good get the test one each of your generators (only need the not running test on the others)

I can get something up and running with this data. I may need additional data at some point but I will let you know.

**Comment by darkstar2002** [comment] 2018-05-01 18:03
Here you go.  400 off and 2 400 running.  They are in manual mode to make them run.  550 off is from our 550kw.  It might be a few days before I can get to our 175kw.
[550_off.txt](https://github.com/jgyates/genmon/files/1964722/550_off.txt)
[400_off.txt](https://github.com/jgyates/genmon/files/1964723/400_off.txt)
[400_on.txt](https://github.com/jgyates/genmon/files/1964724/400_on.txt)
[400_on2.txt](https://github.com/jgyates/genmon/files/1964725/400_on2.txt)

**Comment by jgyates** [comment] 2018-05-01 18:05
Wonderful. Thanks! I will let you know how things progress.

**Comment by darkstar2002** [comment] 2018-05-02 17:56
Here is our 175kw natual gas model.
[175_off.txt](https://github.com/jgyates/genmon/files/1968369/175_off.txt)

**Comment by jgyates** [comment] 2018-05-03 02:46
@darkstar2002 

So far things are going well. Below is what I am getting from the register dump so far (plus alarm conditions. This is from the running 400kw version that you sent:

Status : 

    Engine : 
        Switch State : Manual
        Engine State : Running. Ready for Load. 
        Output Power : 0.00 kW
        Output Power Factor : 1.00
        RPM : 1805
        Frequency : 60.10 Hz
        Throttle Position : 1800 Stp
        Coolant Temp : 118 F
        Coolant Level : 794 Stp
        Oil Pressure : 56 psi
        Oil Temp : 0 F
        Fuel Level : 48
        Oxygen Sensor : 0
        Current Phase A : 0.00 A
        Current Phase B : 0.00 A
        Current Phase C : 0.00 A
        Average Current : 0.00 A
        Voltage A-B : 21.20 V
        Voltage B-C : 21.30 V
        Voltage C-A : 21.30 V
        Average Voltage : 21.30 V
        Engine Hours : 418.1 H
        A-F Duty Cycle : 7.30

    Battery : 
        Battery Volts : 27.82 V
        Battery Charger Current : 0.00 A

    Line State : 
        Transfer Switch State : Unknown

    Time : 
        Monitor Time : Wednesday May 2, 2018 22:39:00
        Generator Time : Tuesday May 1, 2018 11:45:02

If things like run hours and coolant temp do not match, let me know. I made my best guess at info that has decimal places. In general let me know if values are out of range.

There are still a number of items I have yet to locate( utility voltage, log registers, service info). What would help would be a dump of a larger range of registers. When you have time can you run the following:

python.exe modbusdump.py -r 9600 -p COM4 -a 64 -s 0 -e 17000 > out.txt

Also, do a dump and make note of the exercise time, then change the exercise time and do another dump. That will help narrow the search a bit.

**Comment by jgyates** [comment] 2018-05-03 12:43
Found a mistake, Engine hours should be : Engine Hours : 105.5 H

**Comment by darkstar2002** [comment] 2018-05-03 13:52
I do know that the voltage should be 200 something.   I will try to get to the generator today if the weather will corporate.

**Comment by jgyates** [comment] 2018-05-03 13:54
I changed the voltage output to not divide by 10 so it should read 212 in stead of 21.2

**Comment by darkstar2002** [comment] 2018-05-03 17:52
We lost power for a little bit.   Here is our 550 running on lost utility power.    I am also attaching the e version which is what I could get from your 17000 request.  Had to cut it off after 20min due to it starting to rain again.
[550_on.txt](https://github.com/jgyates/genmon/files/1972051/550_on.txt)
[550_on_e.txt](https://github.com/jgyates/genmon/files/1972052/550_on_e.txt)

**Comment by darkstar2002** [comment] 2018-05-03 17:53
Also the engine hours on the 550 is 97.7.  current kw load on this run was around 160-210kw.

**Comment by jgyates** [comment] 2018-05-08 02:13
@darkstar2002 

I have an initial alpha type version up and running under simulation using your supplied dump files. If you want to test you can do the following:

Checkout the latest and install the software as you would normally per the wiki.

Once complete with the installation edit /etc/genmon.conf add/edit the following lines
change

    address=9d

to

    address=64

add this line to the end of genmon.conf

    controllertype=h_100


Things that are missing or not working yet:
* Utility Voltage - this is hardcoded to 240V at the moment.  a larger dump will help fix that
* The bits for transfer switch status appear to act differently on your generators. Will need to look into how they are configured at some point.
* The log registers are not known at this point, a larger dump will help fix that
* Exercise date and time are not implemented,  a larger dump will help fix that

**Comment by darkstar2002** [comment] 2018-05-10 20:04
I was able to look at some of the stuff.   Battery and Fuel level works.  I could not see what it was doing when the generator is on.   I will be ordering hardware soon to hook these up permanently so I do not have to go out with a laptop to try things out.

**Comment by jgyates** [comment] 2018-05-10 20:10
Sounds good. I am working on some things now that should make getting this working easier, for example if you enable email on the system I have an option built in that if you enable it, it will email me the large register dumps automatically so you will not have to run a specific test for that. Of course if you don't want email enabled we can do it the manual way. Also, you can upgrade each system to the latest software via the web interface (assuming the pi has internet access) so that will make updating as I add new functionality.

**Comment by darkstar2002** [comment] 2018-05-17 13:25
Getting one of the pi's ready to on the big generators.  I get a LoadConfig() error from genserv.py

**Comment by darkstar2002** [comment] 2018-05-18 12:57
For what ever reason its working now.     Is there a way to force a email out of your system?   I need to test that it is working.  I have a complex firewall / email system here and just want to make sure its working.

**Comment by darkstar2002** [comment] 2018-05-18 13:54
Never mind its all working.   I have the debug turned on.   Right now I only have our 400 hooked up.

**Comment by darkstar2002** [comment] 2018-05-18 14:01
I had to shutdown the enable debug.  It was throwing serial errors and would not update the dashboard

**Comment by jgyates** [comment] 2018-05-18 15:29
The ClientInterface.py program (you can run it from a PC or the pi) will let you enter a command that will send your log files to me.

If run on the pi type:

     python ClientInterface.py 


If run on a PC include your IP address of the PI you want to communicate with:

     python ClientInterface.py IPADDRESOFPI

Once ClientInterface.py us running (type "exit" to exit the program) you can type:

     generator: sendlogfiles

This will email your error logs to me and allow me to get a better insight into any  problems with ther debug thread.

**Comment by jgyates** [comment] 2018-05-18 17:27
From the console type this command:

     sudo fuser /dev/ttyUSB0

This should return a single number (the process ID of the program using the port). If multiple numbers are returned then we have an problem. If one is returned then I need to keep looking...

**Comment by jgyates** [comment] 2018-05-18 17:42
More question:

What is the model / manufacturer of the USB serial device? If the power requirements for the USB device are too large it could cause problems. 

Which Pi version are you using?

Also make sure the usb device is making a good connection and there is not excessive strain on the connector.

**Comment by darkstar2002** [comment] 2018-05-18 17:47
I only get the errors when the debug is true.  its a plugable serial adapter. Pi 3
fuser only shows one pid for debug on and off.

I had debug off for several hours and had not had any errors come up.

**Comment by jgyates** [comment] 2018-05-18 18:49
OK. What is odd is that I can run the debug thread with no errors. I have a lock in the code that prevents the debug thread from stepping on the normal thread that reads the modbus registers and this is common code for the H-100 and the residential generators so I am fairly confident the debut thread alone is not the issue. I could be the additional throughput the debug thread is putting on the port is causing problem with the USB serial device or the power level is maxing out on the pi.

A couple of things we can to to narrow this down:

1) Run the command: 
       vcgencmd get_throttled

If we get non zeros back we could have a power problem.

2) Open up a couple of consoles so we can monitor some of the system logs. Each one of the commands you can stop with Ctrl+C and each command should be run in a separate console session.

* This will show the syslog:

      tail -f /var/log/syslog

* This will show the messages log:

     tail -f /var/log/messages

* This will show the dmesg log:

     sudo dmesg -wH

If there is a sudden disconnect of the USB device it should log it in one of these logs.

I looked up the power requirements of hte pluggable USB device, it is 100mA. The limit is 500mA for a standard PI 3 I think so unless you have other devices connected the power on the USB should be fine.

How are you powering your pi? I assume you have a ground connection on your serial cable?

I will try to run some tests on my end to see if I can duplicate this issue.

**Comment by darkstar2002** [comment] 2018-05-18 19:15
Running the pi off poe.   serial usb connects to a regular serial cable that goes to the gen controller.  I have no usb disconnects running debug.  the throttled command is  0x50000  I only get a undervolt issue right at startup but it corrects almost immediately.  Its completely good by the time the login screen is up.

**Comment by darkstar2002** [comment] 2018-05-18 19:34
Average Transaction Time : 0.0276 sec
--


With debug off.

**Comment by jgyates** [comment] 2018-05-18 19:37
Interesting, this is a faster packet response than the residential version (.0309 is typical for the residential) . I guess they packed a speedier processor in the big gens..

What is the Packets per second?

**Comment by jgyates** [comment] 2018-05-19 03:50
I made another change to the code that may help. I slowed down the debug thread, it now sleeps 0.25 seconds between modbus reqeust. I should take a bit longer to read the full set of registers but if it works it should be able to do it's thing unattended. Let me know how it goes. on my system (with an average transaction time of 0.309 seconds) it took about 30 min. The way the debug thread works is that it reads registers 0 - 0x2000 (8192 decimal) for 5 passes, each pass takes about 30 min with the current build. After each pass the registers are compared to see what has changed.

Another question. Can you read the utility line voltage from your generator display? With the base registers I have, I have not been able to find registers that correspond to the utility line voltage. Depending on how the transfer switches are setup it is possible that some configurations will not have the utility voltage available to the generator controller.

**Comment by jgyates** [comment] 2018-05-19 19:02
I did some digging on the error that is reported on the serial interface "device reports readiness to read but returned no data (device disconnected or multiple access on port?)" . According to the comment in the code for the serial python library that is generating the error, this error occurs when the device is disconnected. My guess is that it is a power issue, possibly an interaction between you POE injector an the serial USB device's power consumption. The change I checked in may work around this issue, but you could still have problems later. You may consider trying to migrate away from the USB device and move to using the pi's internal serial port as this should greatly reduce the likelihood of this error. Here is the link to the python serial code that generates the error:

https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L520

**Comment by jgyates** [comment] 2018-05-20 06:43
I added email notifications in the H-100 code so you should see and email when it starts, when the engine state changes and when an alarm occurs. Emails during an outage will work once I can determine the utility line voltage.

**Comment by darkstar2002** [comment] 2018-05-20 16:14
I will check tomorrow on if the displays show util voltege.  We have 2 different styles of transferswitchs. 2 dumb and one very very very smart.   Unfortuanly I will be stuck with usb serial.  Everything needs to be completly plug and play.     I may look to see if there is some kind of super capacitor for a usb power system.

Packets per sec is high 67
 I just update the software.  I will try the debug again tomorrow.

**Comment by jgyates** [comment] 2018-05-20 16:20
I have seen issues that people have posted on line regarding the raspberry pi and USB power issues. One of the suggestions was that if power is an issue try using a USB hub since the hub would be powering the USB device instead of the pi.

I have used a serial USB with a pi before, but that was with a different power supply than PoE.

Once you get back to it you may want to test to make sure you see USB disconnects messages in your messages log. If you don't you can update the raspberry pi firmware.

**Comment by darkstar2002** [comment] 2018-05-21 14:12
Here is a big dump.   Looks like after awhile it it cant read the higher numbers.    
[mymodbus.log](https://github.com/jgyates/genmon/files/2022836/mymodbus.log)
[out.txt](https://github.com/jgyates/genmon/files/2022837/out.txt)

**Comment by jgyates** [comment] 2018-05-21 14:29
That is more registers read than some (0x01a5), but the 550 read more on a previous dump (0x02c6). Did not notice any USB disconnects or throttled messages in the log or did the myserial.log file have any errors?

I wonder if the slowed down debug code will work better. I can slow down the main read thread also if we need to. I just checked in a change that will put a small delay between all reads. If you enable the debug thread with this update it may make it farther.

**Comment by darkstar2002** [comment] 2018-05-21 14:36
No error messages in the kernel or myserial

**Comment by darkstar2002** [comment] 2018-05-21 14:44
I have the debug running.   looks like it can run for about 3 or 4 mins before it spits a few errors out then goes ok.
pps is about 27

**Comment by jgyates** [comment] 2018-05-21 16:45
If the errors are timeouts that is not ideal, but OK for the short term. It way the main read thread and the debug thread both work is that they cycle through iterations so if there is a timeout it will pick it up the next time around. Something is not quiet right with the serial comm  that is for sure.

**Comment by darkstar2002** [comment] 2018-05-21 17:37
I can not see on the generators any line voltage.

**Comment by liltux** [comment] 2018-05-21 18:25
FYI 
Industrial H Panels do not sense utility voltage and does not have input for that. They can have switch position available (ie in utility or generator position) if wired up for that feature between the generator and the transfer switch.  H panel generators require a 2 wire start signal (normally open contact) which starts the generator from the transfer switch.

**Comment by jgyates** [comment] 2018-05-21 18:46
@liltux 

Thanks! That is very helpful info.

**Comment by darkstar2002** [comment] 2018-05-21 19:04
We are having a power out test right now.   The graph for kw output is showing 1kw but down below it shows the correct kw.

**Comment by jgyates** [comment] 2018-05-21 19:36
oh, one other thing that would be useful and is easy to do:

If you have the software running, leave the web UI up for about an hour. then go to the registers page by clicking the icon in the top right corner of the web page. This page will show you the modbus registers that are being monitored. You can scroll to the bottom of the page and there are three icons (10 min, 1 hour, and 24 hour). You can print (or save to a PDF if your browsers supports that like Chrome). Print the 10 min and 24 hour outputs to a PDF and post them here. This will let me see what registers are changing over time.

**Comment by jgyates** [comment] 2018-05-24 15:37
I have checked in a few updates so if you get back to testing make sure you pull the latest code (you can update it from the monitor page in the web UI.

I am in the process of making the gauges more flexible in the web page. Eventually this may be user configurable, but in the interim, if I remove Utility Voltage gauge, what value parameter would you like to see added as a gauge on the web interface?

Have you had a chance to try the latest code with the slowed down read? I am curious if the debug thread will read the registers with this code change.

**Comment by darkstar2002** [comment] 2018-05-24 17:50
Debug is a little better.    I was looking into the serial adapter that I have and looks like it is an x model and there are a few issues with it.

**Comment by liltux** [comment] 2018-06-01 15:05
FYI
![image](https://user-images.githubusercontent.com/17954856/40847709-bc6bf380-6582-11e8-8876-92dfaa5cbbf6.png)
![image](https://user-images.githubusercontent.com/17954856/40847748-d1158c7e-6582-11e8-93b0-52be35d2bae3.png)
I am playing around with your genmon, with pi zero w, usb/serial adapter, SD300 H-panel Genset.  Performed update via web ui and the voltage and amperage meters are not correct.  As well as the measured amperage is reading at 34.0-34.4 and should read 340-344, believe multiplier is off.  Just some information for you guys.  Doing great work.

**Comment by jgyates** [comment] 2018-06-01 18:39
@liltux , Thanks for the feedback! I checked in an update that should help. Also your register dump are very helpful also. 

Regarding the settings ui. If you can post the contents of your /var/log/genserv.log file or you can enter this address in your browser:

http://YOURIPADDRESS:8000/cmd/sendlogfiles

substitue YOURPIADDRESS with the IP address of the raspberry pi and it will email me the contents of your log files.

The main hurdle at the moment for the H-100 is not having a large enough dump of registers. It looks like your register dump has about 500 registers. I need around 2000. If you can rum the dump program again that would be great. another method to do this would require less work from you is to enable "Automated Feedback" on the settings page (once we figure out why your settings page is not working) and modify your /etc/genmon.conf file to modify the entry 

from:
     enabledebug = False

to: 
    
     enabledebug = True

This will create a background thread that will read the modbus registers. If "Automated Feedback" is enabled, it will send me the results via email.

The gauges have been updated, but I know they are not quite right yet. Part of the problem is getting enough mobus registers so I can find the nominal kw, voltage and current settings for the generator model. As a result the coloring and maximum values on the gauges will likely be off since I am not reading the voltage and current output settings of the generator yet.

Once I get your logs hopefully we will be able to see the problem with the settings page.

Also, let me know if you see any serial errors on the Monitor page. @darkstar2002 has been having some serial issues, which I think are related to his USB adapter, so if you are not seeing any issues then this will help with that problem as well. 

If you see any thing that is not right let me know.

**Comment by liltux** [comment] 2018-06-01 21:14
I am on a different SD 300, the changes helped with gauges and read out.  But for some reason I click on settings and it does nothing on the web ui.  I did send a (pi ip address)/cmd/sendlogfiles, so hopefully that went through, if not let me know.  The web ui update is working good, great job.  I am using my pe zero as a travel pi.  I work on Generators and thought if i had time I could get some info passed on to you from different generators.  My install was yesterday, git clone etc. followed by a sudo bash genmonmaint.sh install.  the only thing i opted out of was the start on boot.  now that i am typing this i believe i was running the script during some storms and something may not have downloaded or configured right with the power fluctuations.  My pi was powered off of laptop, but my wifi/internet was not.  I might try a fresh install tonight or this weekend and see if there are any improvements.  right now i am doing a modbus "monster" dump, which i will load up here when complete.  Doing a fantastic job, if you need any assistance let me know and i will see what i can and cannot do.

**Comment by jgyates** [comment] 2018-06-01 21:57
I got your logs, nothing is jumping out at me as a problem with genmon or genserv. It may be the javascript. Open your Chrome Settings -> More Tools - > Developer Tools  menu setting. This will bring up the built in Chrome debugger, click on Console. Do you see any messages here?

**Comment by jgyates** [comment] 2018-06-01 23:58
@liltux , Question: you submitted your registers earlier today (6/1/2018). Is that generator a 300kw also?

**Comment by liltux** [comment] 2018-06-02 00:15
@jgyates  yes, everything submitted today was on a 300kw, i did not edit that in the config file correctly first thing this morning.  i will check my browser sometime this weekend as far as javascript issues.  but i did get a "monster" modbus dump for ya.
[sd300_Monster_modbusdump_6-1-18.txt](https://github.com/jgyates/genmon/files/2064498/sd300_Monster_modbusdump_6-1-18.txt)
I tried for a big one, it was processing for about an hr, but only got to 945.

**Comment by jgyates** [comment] 2018-06-02 04:34
Great info! I added some more info on the status and Monitor page. On the status page there are 2 items that I added. I labeled them "Current Status" and "Previous Status", not sure about the "Previous Status" label. 

Looks like your last register dump stopped on and error that was captured in the dump file. I tracked that down and I hopefully fixed that so next time you will get a lager dump. Based on the info the I am finding it looks like there may still be more info to gain from a larger dump than the previous.

Update your software for the latest, let me know if anything is not right or seams odd in the display. 

This is the info I added to the maintenance page:

    Controller : H-100 Controller, PM-DCP Release 4.1
    PM-DCP : PM-DCP Release 4.1C , HW00, $Date: 2015/10/01 15:37:56 $
    Version : 4.0.1, 4.0.0

Not sure what the Version string corresponds to...

This was added to the Status page:

        Current Status : Running from Manual 
        Previous Status : Running from 2-wire 

The Current Status appears to match the registers that I am reading to get the same info, in some cases it has some additional info like key position. the Previous Status is labeled that way because I don't know a better way to label it? Does it correspond to anything on the controller display? 

Still looking for some way to tell the model / kW / voltage configuration....

**Comment by liltux** [comment] 2018-06-02 17:40
@jgyates Good Morning,  so i checked the console.  no errors or warnings, or messages listed when i attempt to click on settings tab.  Still doesn't change.  so the version, release #s all have to do with the firmware version running on the controller.  today i am hooked up to one with a different firmware version.  I also noticed the battery gauge, all industrial gens are 24vdc, some are still 12vdc.  And yes on the:
>his was added to the Status page:
>
>   Current Status : Running from Manual 
>   Previous Status : Running from 2-wire 
>The Current Status appears to match the registers that I am reading to get the same info, in some cases >it has some additional info like key position. the Previous Status is labeled that way because I don't >know a better way to label it? Does it correspond to anything on the controller display?

that would be correct.  running, switch in manual ; running, 2-wire start ; stopped, key switch off ; stopped, 2-wire start.  that should be close, I would have to look into all the different messages.

I will be doing another dump shortly, after i update.

**Comment by liltux** [comment] 2018-06-02 17:46
FYI,
just did a webui update and recived these errors:
![image](https://user-images.githubusercontent.com/17954856/40879234-ba6a277e-6662-11e8-9fe5-54960594e00d.png)
I apologize, im not familiar at all with jquery, jscript, json, or the likes.  I can minimally get around python.

**Comment by liltux** [comment] 2018-06-02 18:49
@MichaelB2018 I will try to repoduce, after my Modbus dump completes.  I also ran genmonmaint.sh install again, this time I noticed a package installed.  so i might have been missing that package and now it may be corrected.  I will post later what i find, thanks.

**Comment by MichaelB2018** [comment] 2018-06-02 18:52
yes, a missing package would explain this. Otherwise this error seems very unusual.

**Comment by jgyates** [comment] 2018-06-02 19:20
I added the package pytz recently, it is not used yet, but there are a copule of things that might simplify the code some if we do start using it. If it was that package then I is not related to modbus.

**Comment by liltux** [comment] 2018-06-02 22:08
I will investigate the webui more later tonight.  But here is a good dump, 1400 registers.
[h-100_modbusdump_6-2-18.txt](https://github.com/jgyates/genmon/files/2065420/h-100_modbusdump_6-2-18.txt)
so this is on an older controller firmware.  should match some of what the newer firmware has, just the newer firmware will have more.

**Comment by jgyates** [comment] 2018-06-03 02:36
Is this from a 300kW also?

**Comment by liltux** [comment] 2018-06-03 02:47
This is from an H-Panel controller programmed for some unit, but not attached.  I have it configured as a testing H-panel.

**Comment by jgyates** [comment] 2018-06-03 03:00
Just out of curiosity, try running the web UI in incognito mode and also try with a different browser. I just want to make sure it is not an issue with and browser extensions.

**Comment by liltux** [comment] 2018-06-03 03:36
give me a few days.  I will be able to test with an evolution air cooled and a h-panel industrial on actual generators.  I tried the settings for air cooled and with settings for h_panel, without being connected to a generator, and the settings page pulled up both times.

**Comment by ewouk61** [comment] 2018-06-08 11:41
model: QT02524KNSNA
some potential enhancements for the industrial gens
  the graphic for the battery gauge have 2 green zones, one for 12v systems and another for 24v. it read the voltage fine, its just that some industrials are 12v and some 24v.
  the h panel tells you the the battery charger current, but when the generator is running the battery charger current number is wrong. this is a generac issue not a genmon problem. just fyi
  for block heaters, unless you have orders a special one or have one that is 240v they usually turn on at 60f and off at 90f. when i have a block heater that burns out i replace it with a 100 on-120 off model.
  the genmon showed the output voltage correctly, just the colored section of the graphic was a little off for a 480v gen, need to go check a 3 phase 208 one next. maybe a drop down menue where you select the output voltage scale would be useful?

**Comment by ewouk61** [comment] 2018-06-08 11:44
also a water temp between 170 and 200 is a normal range for a gen. most have a 180f thermostat

**Comment by jgyates** [comment] 2018-06-08 13:06
@ewouk61 

Thanks for the info. I will make these changes. One one of the issues I have with the H-100 is that I have not figured out how to read the voltage the configuration yet. A menu selection may be the best way until I can decode the modbus for that parameter properly.

**Comment by jgyates** [comment] 2018-06-08 13:10
@ewouk61 

You mentioned that "my pi 3 b cpu is at 30% on the status page, but 5% on the others" Can you give me more details on this? The cpu utilization is is higher when the system first starts but should ramp back down to around 2-5%. Are you saying that your industrial gen always at 30% but other non-industrial gens at 5?

**Comment by jgyates** [comment] 2018-06-09 02:22
I checked in a new version that has a few updates for H-100:

1) Added two settings for H-100 on the settings page of the web interface (Nominal Battery Voltage and Voltage Configuration)
2) Update gauge coloring / max values for Coolant Temp, Average Current, Average Voltage gauges 

I made my best guess on the max value of the Average Current gauage (max watts / Nominal Line to Line Volts). 

Let me now if you have any questions or if you see anything that needs to be corrected.

**Comment by liltux** [comment] 2018-06-09 02:49
I've been busy this week, but hoping to get something put together this weekend with a pi zero w.  Been following the thread updates just need to get the latest changes and try it out. And to add to @ewouk61 voltage suggestion, liquid cooled gens either h-panel or Evolution can be either:
60 hz 240 1ph
60 hz 240 3 ph Delta
60 hz 208 3 ph low wye
60 hz 480 3 ph high wye
And let me know if you want the 50hz options, I will have to look those up.  I don't know those off the top of my head.

**Comment by jgyates** [comment] 2018-06-09 16:42
Just checked in V1.9.23. This will make the pages in the web UI that are not supported yet not show up if you are running an H-100 (logs and outage page)

**Comment by jgyates** [comment] 2018-06-11 18:10
I added this page to the wiki:

https://github.com/jgyates/genmon/wiki/Appendix-7-Generac-H-100-Controller

Let me know if there are any additions that need to be made.

**Comment by liltux** [comment] 2018-06-20 16:31
@jgyates , everything looks outstanding!!  I am currently hooked up to a 600kw diesel, i can access all web app pages.  As far as I can tell it is working correctly.  Great job!  I also submitted registers via web ui.

**Comment by jgyates** [comment] 2018-06-20 21:01
@liltux, Thanks for the feedback. I did not receive your registers. To send the registers it requires that email is setup.

**Comment by liltux** [comment] 2018-06-20 21:57
@jgyates, yes i don't believe i had my email setup correctly.  I will get that lined out for the next one i get working.

**Comment by liltux** [comment] 2018-06-22 12:42
@jgyates do you have a better forum for me to send you messages?  I just submitted registers from a Synergy Evolution controller.  Can also do a modbus dump later on this unit as well.  I am sure it will be close if not the same to Evolution controller but there may be some differences and thought you might like the info.

**Comment by jgyates** [comment] 2018-06-22 15:20
I can respond to your register submission in email if that is an email address that you monitor. Let me know if that works.

**Comment by jgyates** [comment] 2018-06-22 17:40
I just checked in an update that should help for the Synergy Evolution.

**Closed** 2018-08-12 21:08 UTC
Labels: question

**Comment by jgyates** [comment] 2018-10-30 15:07
I posted an update for H-100 controllers. This version (V1.11.18) also has the initial release for G-Panel controllers. If you update, let it run for about 1 min then submit your logs / registers on the about page. This data will help me validate and potentially add more data to the display. Logs and additional info on the maintenance page are included in the update as well as better handling of alarms.

**Comment by darkstar2002** [comment] 2018-10-30 15:29
I did one of our gens.  I sent you the info.  Hope you got it ok.

**Comment by liltux** [comment] 2018-10-30 15:29
@jgyates looking Good!

**Comment by jgyates** [comment] 2018-10-30 15:40
@darkstar2002 and @liltux  , yes I got it. thanks

**Comment by jgyates** [comment] 2018-11-01 00:55
I just posed another update for H-100 and G-Panel. You will likely not notice anything new, but there were some improvements relating to modbus parameter validation.
