### ISSUE TITLE
If MsgType 'Info' not set, no logs or registers submitted

### ISSUE THREAD

**Issue by smeisner** [jgyates/genmon#680] opened 2022-03-01 17:48 UTC
Feel free to close this if you think it's not appropriate. During a recent debugging event with you, I was unable to send my logs or registers using the UI buttons. After a lot of digging I finally found out why. Somehow the MsgType of Info got cleared. Due to that, I was missing many updates and unable to send my logs. 

Under Notifications, I clicked the box to the right of my email and "Info" was not selected. Once I added that, everything appeared to work as expected.

I could create a PR for this fix if wanted.

### Expected Behavior

Either be notified Info type was not set, or it be called out in the log files. Maybe something like "Exception: MsgType 'Info' unset" in the log file.

### Actual Behavior

 Error SMTP sendmail: {'<>': (501, b'5.1.3 Bad recipient address syntax')} : mymail.py:473
 Error in SendMailThread, sendEmailDirectMIME failed, retrying

### Steps to Reproduce (including precondition)

Clear the Info tag in the Notifications page, then perform an email test in the Settings page.

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: G0060331
- Genmon Logs: Done 2 times while testing today
- Genmon Version: V1.18.07 (I have updated after testing to V1.18.08)

**Comment by jgyates** [comment] 2022-03-01 19:53
I got both of your registers submissions. I checked in a fix for this. The issue is that if a mail message was being sent without a category recipient then it would still be put in the queue to be sent. It would fail to be sent successfully so it would be re-queued to be tried again in 2 min. What should happen is that it should not be sent in the first place. 

Logs and registers emails are always sent as the recipient it always generatormonitor.software@gmail.com, however the issue was that an initial message was in the queue and failing (the startup notice email) so the other emails would not be sent until the first one was sent successfully, which it never would since there is not recipient. Failed emails are re-queued with the idea that they would be sent at a later time if there was an internet outage.

The log will not show messages that are not send if not category is available unless debug=True is in the /etc/genmon/mymail.conf file. It is not logged by default since I try to only log errors unless there is a good reason as excessive log file writing is not great for the SD card lifetime.

I guess I have not seen this issue before because most folks use all the categories in the email notifications.

Thanks for the followup on this. This was a bug that would have been difficult to find otherwise.

**Closed** 2022-03-01 19:54 UTC
Labels: bug, email
