### ISSUE TITLE
Enhanced exercise dispaly problem

### ISSUE THREAD

**Issue by UPS99** [jgyates/genmon#678] opened 2022-02-24 17:42 UTC
FYI only - a small settings oddity - I noticed today that the Enhanced Exercise function was showing "off", despite the fact that it is actually enabled and has been working OK - running for the 10 minutes I have set.  Selecting "on" prompted with those previous settings still filled out.  Genmon then restarted and appears normal, and Enhanced Exercise now shows "on".  I don't know when this changed - just happened to notice it today.

**Comment by jgyates** [comment] 2022-02-25 03:43
Thanks, I will keep an eye out for the cause of this. At the moment it is not obvious to me what the issue may be.  I am going to close this for now as I don't have any actions I can take, but I will update this if I have a resolution.

**Closed by jgyates** 2022-02-25 03:43 UTC
Labels: bug

**Comment by UPS99** [comment] 2022-02-25 04:28
That’s fine.  I just wanted to provide this limited info in case it would be useful.  Unfortunately I didn’t notice which update it followed.
