### ISSUE TITLE
Test Email Settings does NOT work

### ISSUE THREAD

**Issue by jcleek** [jgyates/genmon#759] opened 2022-09-10 22:05 UTC
### Expected Behavior

Test Email Settings button would test the settings provided and attempt a test email. I can assure you the information is correct in the SMTP settings, and GenMon in fact PROVES they are correct because when I restart GenMon I get emails telling me it is starting. Then if I immediately go to the settings page and click the test button it fails. I spent an hour trying to figure out why I couldn't get matching credentials for Office 365 when I knew for a fact I had the right account and app password so I power cycled the Pi, and I started getting generator notices. I wasted an hour because the test does not work.

### Actual Behavior

Fails to log in with error attached

### Steps to Reproduce (including precondition)

Click the button

### Screenshot or Pictures relating to the problem (if possible)

Attached
### Your Environment

- Generator Model: Generac 17kW
- Genmon Logs: Done
- Genmon Version: V1.18.14
![GenMon error](https://user-images.githubusercontent.com/16121417/189503221-0e1477fd-903c-462a-a16b-24db3f5209ad.png)

**Comment by jcleek** [comment] 2022-09-10 22:09
Side note, I don't mean to seem ungrateful for the project. I love it. But this was pretty frustrating to find out I had the right settings but the test just isn't working.

**Comment by skipfire** [comment] 2022-09-10 23:12
I also use Office 365 and the test works for me.  Are you using any extended characters?

**Comment by jgyates** [comment] 2022-09-10 23:28
I just tested and I am getting and the same error using an old hotmail address and I am seeing the same error. Not sure what the issue is but it looks like something changed on the microsoft end since this code has not changed in a while. This used to work. 

Until I can track this down I would suggest using a gmail address instead. Note that gmail requires an app specific password to be created. See this thread: https://github.com/jgyates/genmon/issues/682

I am guessing this is some increase in security from microsoft.

**Comment by jcleek** [comment] 2022-09-10 23:41
App Passwords are auto-generated and weirdly enough they do NOT use anything more than letters and numbers. No characters at all.

As I said, with the correct settings email is sent. I get the notice that it is starting and in AUTO mode after the restart.

**Comment by jcleek** [comment] 2022-09-10 23:42
@skipfire do you have 2 factor turned on for the account you are using? I suspect this may be related to app passwords in O365.

**Comment by skipfire** [comment] 2022-09-10 23:45
@jcleek nope.

**Comment by jcleek** [comment] 2022-09-10 23:50
I am using 2 factor and an app password. Hopefully that helps @jgyates

**Comment by jgyates** [comment] 2022-09-10 23:58
@jcleek 

After looking at this further, my test does appeqar to be working. My initail tests from hotmail were going into my junk folder. 

If I save my setting I do see one error from smtplib on the initial login "Lookup failed" but I think that is due to my ISP, however the code continues as the server is authenticated and the email is sent. I can send test messages also.

Try this: log into  your pi via ssh and valiate your settings in the /etc/genmon/mymail.conf file. Do these match your expected settings for your email account?

**Comment by jcleek** [comment] 2022-09-11 00:01
@jgyates yes the settings there are correct. The password in there is the new app password I created.

**Comment by jgyates** [comment] 2022-09-11 00:09
ok. the error I was seeing was because I had IMAP enabled on my setup but still had the gmail IMAP address. Presently I am using hotmail and getting not errors. sorry that it took a minute to get my MS email setup working, it has been a while since I used this, but it does appear to work. 

To recap, you issue is that the test email does not work but the email sent when genmon starts does not? is that correct? If that is the case please send me your logs from the about page.

**Comment by jcleek** [comment] 2022-09-11 01:11
Test does not work. When I restart the Pi I get two emails:

Time: 08:58:41 PM
Date: Sat 10-Sep-2022
Generator Monitor Starting 

===================

Time: 09:00:00 PM
Date: Sat 10-Sep-2022

NOTE: This message is a notice that the state of the generator has changed. The system is not in alarm.

Status : 

    Engine : 
        Switch State : Auto
        Engine State : Off - Ready
        Battery Voltage : 13.30 V
        RPM : 0 
        Frequency : 0.00 Hz
        Active Rotor Poles (Calculated) : 0 

    Line : 
        Utility Voltage : 249 V
        Utility Max Voltage : 249 V
        Utility Min Voltage : 249 V
        Utility Threshold Voltage : 133 V

    Last Log Entries : 

        Logs : 
            Alarm Log : 06/03/22 12:48:54 RPM Sense Loss 
            Run Log : 09/09/22 11:12:11 Stopped - Auto 

    Time : 
        Monitor Time : Saturday September 10, 2022 20:59:59
        Generator Time : Saturday September 10, 2022 20:59

**Comment by jgyates** [comment] 2022-09-11 01:27
Can you send your logs? I have not received anything yet. You do this by clicking the submit logs button on the about page.

Also, can you validate that you are moving the cursor focus out of any of the email settings before you click the "Test Email Settings"

If you save your settings and the emails go out, then click the "Test Email Settings" button, do you still get the error?

**Comment by jcleek** [comment] 2022-09-11 01:29
Just did again to generatormonitor.software@gmail.com

**Comment by jcleek** [comment] 2022-09-11 01:29
And forwarded just in case O365 is blocking the initial email

**Comment by jgyates** [comment] 2022-09-11 01:36
are there any non ASCII characters in the sender email address?

**Comment by jcleek** [comment] 2022-09-11 01:48
No, all letters and an @ of course.

**Comment by jgyates** [comment] 2022-09-11 01:56
Is this a public address (i.e. a free account) or is this email account part of an organization and managed by active directory or some other cloud platform?

**Comment by jgyates** [comment] 2022-09-11 01:58
This could be the issue:

https://stackoverflow.com/questions/72805301/authentication-error-trying-to-send-outlook-email-from-python

If you have a setting in Active directory you can try that or you can try to enable the "Disable SMTP Auth" setting in the genmon email settings.

**Comment by jcleek** [comment] 2022-09-11 02:07
It is a business O365 account. It worked fine when I didn't have 2 factor on.

You asked about SMTP Auth, so I flipped the switch in GenMon and tried again. Failed with the connect() error. flipped it back and test message went.

I have no idea why it works now. I changed nothing.

**Comment by jcleek** [comment] 2022-09-11 02:08
Tested 5 times, all 5 times passed. No clue.

**Comment by jgyates** [comment] 2022-09-11 02:30
I am glad it is working, not sure what the issue was but I am going to close this issue since we can not duplicate this at this point. Feel free to post here if you have any follow up data.

**Closed by jgyates** 2022-09-11 02:30 UTC
Labels: email
